workflows:
  flutter-workflow:
    name: oncesocial
    environment:
      groups:
        - keystore_credentials  # Ensure this group exists in CodeMagic with Android keystore vars
      flutter: stable
    scripts:
      - npm install -g firebase-tools
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - fayyaadh404@example.com
      scripts:
        - echo "Publishing to Firebase App Distribution..."
        - firebase appdistribution:distribute build/app/outputs/apk/release/app-release.apk \
          --app "$FIREBASE_APP_ID" \
          --groups testers \
          --token "$FIREBASE_TOKEN"