// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRL2GVl5nycuW529daGXcM6jyBU1-CCY0',
    appId: '1:1031977312503:web:117097e57a41832bb7f3f2',
    messagingSenderId: '1031977312503',
    projectId: 'oncesocial-201b1',
    authDomain: 'oncesocial-201b1.firebaseapp.com',
    storageBucket: 'oncesocial-201b1.firebasestorage.app',
    measurementId: 'G-327KNHFL3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGOp3TSzody_WWU_cG1Q4rdcCgl0zpbac',
    appId: '1:1031977312503:android:60ced8e0cd197111b7f3f2',
    messagingSenderId: '1031977312503',
    projectId: 'oncesocial-201b1',
    storageBucket: 'oncesocial-201b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLw_JwaQ4uY1m5c9PlMxJK0uY4S2GIIiA',
    appId: '1:1031977312503:ios:bef21ac2ef0902bfb7f3f2',
    messagingSenderId: '1031977312503',
    projectId: 'oncesocial-201b1',
    storageBucket: 'oncesocial-201b1.firebasestorage.app',
    iosBundleId: 'com.once.oncesocial.oncesocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLw_JwaQ4uY1m5c9PlMxJK0uY4S2GIIiA',
    appId: '1:1031977312503:ios:bef21ac2ef0902bfb7f3f2',
    messagingSenderId: '1031977312503',
    projectId: 'oncesocial-201b1',
    storageBucket: 'oncesocial-201b1.firebasestorage.app',
    iosBundleId: 'com.once.oncesocial.oncesocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRL2GVl5nycuW529daGXcM6jyBU1-CCY0',
    appId: '1:1031977312503:web:2b3c232f1a8eae73b7f3f2',
    messagingSenderId: '1031977312503',
    projectId: 'oncesocial-201b1',
    authDomain: 'oncesocial-201b1.firebaseapp.com',
    storageBucket: 'oncesocial-201b1.firebasestorage.app',
    measurementId: 'G-0EYFDFE099',
  );
}
